### ISSUE TITLE
Center Start Surveying! buttons

### ISSUE THREAD

**Issue by bertspaan** [nypl-spacetime/surveyor#115]

**Comment by bertspaan** [comment]
Also this one:

![image](https://cloud.githubusercontent.com/assets/1194896/25705421/3e3b664c-30ab-11e7-9a9e-e37ab080fb2e.png)

**Comment by todrobbins** [comment]
![image](https://cloud.githubusercontent.com/assets/158590/25712493/0ff41db6-30af-11e7-9aa1-e6aed95b4981.png)

**Comment by bertspaan** [comment]
@todrobbins Haaaa! Yes! 

https://github.com/nypl-spacetime/surveyor/blob/accessible/app/containers/Error/styles.js#L27
