### ISSUE TITLE
Keyboard navigation broken for single pane view mode

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/surveyor#150]
When user is setting camera angle task is in single pane mode and reviewing the _item_. Tabbing navigation takes user off page to camera because the drag elements need refinement. Bert to elaborate.

**Comment by bertspaan** [comment]
![image](https://user-images.githubusercontent.com/1194896/26852437-4ec2797e-4adc-11e7-90c8-e15c8792b68b.png)

**Comment by bertspaan** [comment]
Caused by mistake in Leaflet.GeotagPhoto. Fixed!
